### ISSUE TITLE
`directives` attribute should be removed from `mso_schema_template_contract` resource and data source

### ISSUE THREAD

**Issue by danischm** [CiscoDevNet/terraform-provider-mso#198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

`directives` are configured at the filter and not the contract level. `mso_schema_template_contract_filter` resource and data source already have the attribute.

**Comment by andbyrne** [comment]
The `directives` are still required to create the filter relationship, however this should ideally be moved as an attribute in the filter_relationship block since they could be different between each filter.

There are some conflicts regarding filters between `mso_schema_template_contract` and `mso_schema_template_contract_filter`. A contract cannot be created without at least one filter being provided (enforced in NDO4.1), and `mso_schema_template_contract_filter` does not check for existing references.

`mso_schema_template_contract` also only accounts for a `filter_type` of `oneWay` vs `bothWay`, and doesn't allow for the direction to be defined for a `oneWay` filter. The supplied list of filters always get installed under `filterRelationships` (only used for `bothWay`) instead of `filterRelationshipsProviderToConsumer` or `filterRelationshipsConsumerToProvider`.
