### ISSUE TITLE
Terraform context VS NDO context

### ISSUE THREAD

**Issue by jjman4** [CiscoDevNet/terraform-provider-mso#251]
Dear all,

As a terraform/MSO beginner, i've faced with an annoying behavior. 
Our network team are still using the NDO. Therefore, when terraform is applied/deployed and some ongoing change is made via NDO: both changes are applied to all sites.
My question is how can we separate the change context initiated by terraform and the context for any manuel change done via NDO.

Thank you again for your help.

Br,
J.

**Comment by lhercot** [comment]
Hi @jjman4 

Combining manual changes using the UI with an automation tool such as Terraform is possible but not easy to implement.
The main issue is concurrent changes or reverting changes because manual changes have not been adapted in the code.

If you cannot separate the two by using separate schemas or templates, you then have to be careful to always run a `terraform plan` before applying and analyze if the proposed changes are ok or if the terraform HCL code need to be updated because those manual changes should be kept.

There is no magic solution here.

Let us know if you have additional questions.

**Comment by jjman4** [comment]
Hi @lhercot 
Thank you for you feedback.
Is there any way to only apply change done by a specific user in terraform? Usually, any manual change is done by a nominative user and terraform uses his own NDO username.
Another idea, check if some change is pending in the current template/schema. If so, backup or remove it, then apply the terraform change.

thank you.

Br,
J.

**Comment by lhercot** [comment]
This is not something the Terraform provider is designed to do or should be doing.
This logic might be able to be build outside of the provider but this does not sounds like a manageable solution and add a lot of complexity.

Cisco Partners or Cisco professional services might be able to help you build a solution that achieve your goal if you are not looking to build it yourself.

As this is outside of the provider realm, I will be closing this issue.
