### ISSUE TITLE
Inconsistent results when assigning multiple sites to a template

### ISSUE THREAD

**Issue by jufonsec** [CiscoDevNet/terraform-provider-mso#3]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.29
+ provider.mso v0.1.3

### MSO version

* V 3.0(2d)

### Affected Resource(s)

* mso_schema_site

### Terraform Configuration Files

https://gist.github.com/jufonsec/a14c70c21e40218cea1010e12481470f

### Actual Behavior

Try to assign two sites to the same MSO template. Inconsistencies are produced and only one site is assigned.

### Steps to Reproduce

# terraform apply
<snip>
Error: Provider produced inconsistent result after apply

When applying changes to mso_schema_site.shared-site, provider
"registry.terraform.io/-/mso" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
<snip>

**Comment by nkatarmal-crest** [comment]
@jufonsec This is happened because of concurrent behavior of terraform, it will create these sites at the same time using threads. Because of that, situation like lost update problem will occur and the resource which be created last will only be stored at the server and for another resource, it will throw error stating "Inconsistent result". So concluding that create call was successful in both site resources but will fail in read call in any one of the resources.

### Solution
Use parallelism=1 functionality of terraform.

### Terraform configuration file

`
resource "mso_schema_site" "site1" {
  schema_id      = "5fd9ed663800003dce2638b8"
  site_id        = "5ebb1fb61100003a019e0c28"
  template_name  = "Template1"
}

resource "mso_schema_site" "site2" {
  schema_id      = "5fd9ed663800003dce2638b8"
  site_id        = "5ebba69f110000b5039e0c29"
  template_name  = "Template1"
}
`

Note: Schema and site ids are hardcoded.

### Steps to solution

`terraform apply -parallelism=1` 

Let me know if you have any other queries.

**Comment by danischm** [comment]
https://github.com/ciscoecosystem/mso-go-client/pull/105

**Comment by niksheridan-ops** [comment]
may be helpful  - this would provide you with an option to generalise the use of this parameter (eps. in workflows, although arguably it could just be part of a scripted parameter) - this was taken from [here](https://github.com/hashicorp/terraform/issues/27765)

```
export TF_CLI_ARGS_apply="-parallelism=1"
terraform apply
```

**Comment by danischm** [comment]
This should be fixed now from v0.8.0.

**Comment by lhercot** [comment]
Closing this issue. As @danischm mentioned this should be fixed in v0.8.0 and later.

Please re-open the issue if you still have the issue.
