### ISSUE TITLE
Terraform MSO Provider unable to create stretched VRF in template for physical ACI and CloudAWS 

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/terraform-provider-mso#4]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.5
Provider version: 0.1.2
### MSO version

MSO is 3.0.2d

### APIC version and APIC Platform for Site Level Resources
ACI is 5.0.2e for onPrem and CloudAWS

### Affected Resource(s)

*Unable to create stretched VRF between physical ACI Fabric and AWS ACI Fabric.   
*I also tried only to create the VRF for just AWS cloud site and it complains that the region/CIDR/Subnet information was not configured even though it was.

### Terraform Configuration Files

https://github.com/soumukhe/terraformMSO

Directory Structure:
aciadmin@ubuntu-jump:~/Terraform/ACI$ tree
.
├── mso
│   ├── mso-main.tf
└── mso_modules
    ├── mso_provider.tf
    ├── resources.tf
    ├── vars.tf
    └── versions.tf

### Error when Run:
 
Error: "Bad Request: On Site AWS-Site-2 : VRF vrf1 should have a Region associated with it."{}
 
  on ../mso_modules/resources.tf line 55, in resource "mso_schema_template_vrf" "vrf1":
  55: resource "mso_schema_template_vrf" "vrf1" {

Please note that the region/CIDR/Subnet/Hub Network is configured in the resources.tf file.   Currently I have commented the section for the VRF.   So, what I have right now uncommented is the building of Tenant, Schema, SharedTemplate between 2 physical Site and 1 AWS cloud Site.    Next step is to create a stretched VRF in the template.  

 If you follow the UI  workflow, you create the VRF in the sharedTemplate and then you go to siteLocal for cloud site and configure the Region/Subnet/HubNetwork information.  This is the part that is failing in the Terraform Provider which then does not let me proceed to the next step of adding the Region/CIDR/Subnets/Hub network information.

Also, the example for the resource block "mso_schema_site_vrf_region"   is very misleading.  The subnet value does not even fall in the cidr range and that makes no sense.

**Comment by JoaoUrtigaMelo** [comment]
👍

**Comment by andrewb3000** [comment]
This might be helpful - https://github.com/CiscoDevNet/terraform-provider-mso/issues/7#issuecomment-766682447

> The example I have use PATCH API to achieve this. They might have issue when destroy is called if used in a separate plan.
Example using PATCH with AWS site: https://github.com/lhercot/terraform-mso-demo_aws/blob/master/main.tf
Example using PATCH with Azure site: https://github.com/lhercot/terraform-mso-demo_azure/blob/master/main.tf

**Comment by soumukhe** [comment]
Thank You so much Andrii !

I will look into this this week.   However I do want to comment that using rest api’s for Terraform / ACI defeats the purpose of using Terraform, since no Terraform state will be kept.

Regards


[signature_706016245]
   SR. Technical Leader,   ACI Practices, Cisco Systems
      CCIE # 2938  Routing & Switching,  SP-Wan
      HashiCorp Certified: Terraform Associate
        Kubernetes Certified Administrator
        AWS Certified Solutions Architect Associate
        VCP 4.0 & 5.0

   2200 E. Pres. George Bush Trnpk
   Richardson,  TX 75082,  USA
   Phone # 469-255-1813



From: Andrii Bryndzak ***@***.***>
Reply-To: CiscoDevNet/terraform-provider-mso ***@***.***>
Date: Saturday, May 15, 2021 at 11:36 AM
To: CiscoDevNet/terraform-provider-mso ***@***.***>
Cc: Soumitra Mukherji ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-mso] Terraform MSO Provider unable to create stretched VRF in template for physical ACI and CloudAWS (#4)


This might be helpful - #7 (comment)<https://github.com/CiscoDevNet/terraform-provider-mso/issues/7#issuecomment-766682447>

The example I have use PATCH API to achieve this. They might have issue when destroy is called if used in a separate plan.
Example using PATCH with AWS site: https://github.com/lhercot/terraform-mso-demo_aws/blob/master/main.tf
Example using PATCH with Azure site: https://github.com/lhercot/terraform-mso-demo_azure/blob/master/main.tf

**Comment by anvitha-jain** [comment]
This issue is resolved, and the changes are in #52. This will be soon be available in the next release.
Few recommendations for terraform configuration file.
After you add VRF at template level (mso_schema_template_vrf), use mso_schema_site_vrf to add VRF to site the add region to it using mso_schema_site_vrf_region and then add CIDR (mso_schema_site_vrf_region_cidr). Also, we recommend using implicit relationships to avoid order of execution issues.

The configuration file should look like:

resource "mso_schema" "schema1" {
  name          = "schema1"
  template_name = "template_name1"
  tenant_id     = data.mso_teanat.tenant1.id
}

resource "mso_schema_site" "site3" {
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.site3.id
  template_name = mso_schema.schema1.template_name
}

resource "mso_schema_template_vrf" "vrf1" {
  schema_id        = mso_schema.schema1.id
  template         = mso_schema_site.site3.template_name
  name             = "vrf_name1"
  display_name     = "vrf_name1"
  layer3_multicast = false
  vzany            = false
}

resource "mso_schema_site_vrf" "foo_schema_site_vrf" {
  template_name = mso_schema_site.site3.template_name
  site_id       = data.mso_site.site3.id
  schema_id     = mso_schema.schema1.id
  vrf_name      = mso_schema_template_vrf.vrf1.name
}

resource "mso_schema_site_vrf_region" "vrfRegion" {
  schema_id          = mso_schema_site_vrf.foo_schema_site_vrf.schema_id
  template_name      = mso_schema_site_vrf.foo_schema_site_vrf.template_name
  site_id            = mso_schema_site_vrf.foo_schema_site_vrf.site_id
  vrf_name           = mso_schema_site_vrf.foo_schema_site_vrf.name
  region_name        = "us-east-1"
  vpn_gateway        = false
  hub_network_enable = true
  hub_network = {
    name        = "TGW"
    tenant_name = "infra"
  }
  cidr {
    cidr_ip = "10.140.0.0/16"
    primary = true
    subnet {
      ip   = "10.140.1.0/24"
      zone = "us-east-1a"
      #usage = "sdfkhsdkf"
    }
  }
}

resource "mso_schema_site_vrf_region_cidr" "vrfRegionCidr" {  # this did not work either.
  schema_id = mso_schema_site_vrf_region.vrfRegion.schema_id
  template_name = mso_schema_site_vrf_region.vrfRegion.template_name
  site_id = mso_schema_site_vrf_region.vrfRegion.site_id
  vrf_name = mso_schema_site_vrf_region.vrfRegion.vrf_name
  region_name = "us-east-1"
  ip = "10.140.0.0/16"
  primary = false
}
